### ISSUE TITLE
FuncImplSet_mac.h depend on a file as fault name.

### ISSUE THREAD

**Issue by Mike7Chu** [TargetExpert/TargetExpert#1]
TargetExpert/src/LLL/AVR/Common/Macro/FuncImplSet_mac.h
Line 22: #include "BasicFunc_**m**ac.h"  --> #include "BasicFunc_**M**ac.h"

**Comment by GabrielKim** [comment]
This issue has been solved.
Please refer to "21af380d4866798992093edeceb77f2d3e4c89ae".

Thanks.
